// Tests for the offline node-locked licensing (domain/Licensing + MachineFingerprint).
//
// Two halves:
//   1. CROSS-LANGUAGE: a license signed by the pure-Python vendor signer
//      (scripts/licensing) must verify in the C++ OpenSSL verifier — proving the
//      canonical-JSON form byte-matches (incl. non-ASCII UTF-8) and Ed25519 agrees.
//   2. FULL FLOW: with a throwaway key set via setPublicKeyForTesting, sign a
//      license for THIS machine's real signals and exercise evaluate/install/check,
//      plus the negative cases (tamper, wrong machine, expired).

#include "framework/TestStats.h"

#include "domain/Licensing.h"
#include "domain/MachineFingerprint.h"

#include <QByteArray>
#include <QDate>
#include <QJsonDocument>
#include <QJsonObject>

#include <openssl/evp.h>

namespace pharmadesk_tests {
namespace {

// Generate an Ed25519 key pair; return (pub b64, EVP_PKEY*). Caller frees the key.
EVP_PKEY *genKey(QString *pubB64)
{
    EVP_PKEY *pkey = nullptr;
    EVP_PKEY_CTX *ctx = EVP_PKEY_CTX_new_id(EVP_PKEY_ED25519, nullptr);
    if (ctx && EVP_PKEY_keygen_init(ctx) == 1) {
        EVP_PKEY_keygen(ctx, &pkey);
    }
    EVP_PKEY_CTX_free(ctx);
    if (pkey) {
        unsigned char raw[32];
        size_t len = sizeof(raw);
        if (EVP_PKEY_get_raw_public_key(pkey, raw, &len) == 1 && len == 32) {
            *pubB64 = QString::fromLatin1(QByteArray(reinterpret_cast<char *>(raw), 32).toBase64());
        }
    }
    return pkey;
}

// Sign canonicalPayload(payload) with `pkey`, return payload with "sig" set.
QJsonObject sign(EVP_PKEY *pkey, QJsonObject payload)
{
    const QByteArray msg = Licensing::canonicalPayload(payload);
    QByteArray sig(64, '\0');
    size_t siglen = sig.size();
    EVP_MD_CTX *ctx = EVP_MD_CTX_new();
    if (ctx && EVP_DigestSignInit(ctx, nullptr, nullptr, nullptr, pkey) == 1) {
        EVP_DigestSign(ctx, reinterpret_cast<unsigned char *>(sig.data()), &siglen,
                       reinterpret_cast<const unsigned char *>(msg.constData()), msg.size());
    }
    EVP_MD_CTX_free(ctx);
    payload.insert(QStringLiteral("sig"), QString::fromLatin1(sig.left(siglen).toBase64()));
    return payload;
}

QJsonObject currentMachineSignals()
{
    QJsonObject o;
    const auto sig = MachineFingerprint::collectSignals();
    for (auto it = sig.constBegin(); it != sig.constEnd(); ++it) {
        o.insert(it.key(), it.value());
    }
    return o;
}

} // namespace

TestStats run_licensing_tests(QSqlDatabase, qint64)
{
    TestStats s;
    s.module = QStringLiteral("licensing");

    // ── 1) Cross-language: Python-signed license verifies in C++ ─────────────
    // Fixture generated by scripts/licensing with a fixed secret (bytes 1..32).
    // Includes a non-ASCII licensee to exercise UTF-8 canonical agreement.
    const QString fixturePub = QStringLiteral("ebVWLo/mVPlAeLES6KmLp5AfhTrmlb7X4OORC60ElmQ=");
    const QString fixtureLicense = QString::fromUtf8(
        "{\"v\":1,\"licensee\":\"Caf\xC3\xA9 M\xC3\xA9"
        "dico Pharmacy\",\"signals\":{\"machine_id\""
        ":\"aa11\",\"mac\":\"bb22\",\"disk\":\"cc33\"},\"issued\":\"2026-01-01\",\"expiry\":"
        "\"2027-12-31\",\"sig\":\"uyajS0BEBJEYbS4X1fJWTruKK8Y5A8PwjSReM3MvGUyQ52KblYCsf335cwEmLar"
        "js8Lik+4e/LgYKTtTOYCYCQ==\"}");
    bool parsed = false;
    const QJsonObject fx = Licensing::parseLicenseText(fixtureLicense, &parsed);
    s.check(parsed, QStringLiteral("fixture license parses"));
    s.check(Licensing::verifyDetached(fixturePub, fx),
            QStringLiteral("Python-signed license verifies in C++ (canonical + Ed25519 agree)"));
    {
        QJsonObject tampered = fx;
        tampered.insert(QStringLiteral("licensee"), QStringLiteral("Someone Else"));
        s.check(!Licensing::verifyDetached(fixturePub, tampered),
                QStringLiteral("editing a field breaks the signature"));
    }
    s.check(!Licensing::verifyDetached(
                QStringLiteral("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="), fx),
            QStringLiteral("a different public key rejects the license"));

    // ── 2) Full flow against THIS machine, with a throwaway key ──────────────
    const QString savedKey = QString(); // production embeds empty by default
    QString testPub;
    EVP_PKEY *pkey = genKey(&testPub);
    s.check(pkey != nullptr && !testPub.isEmpty(), QStringLiteral("generated a test key pair"));
    if (pkey) {
        Licensing::setPublicKeyForTesting(testPub);
        s.check(Licensing::configured(), QStringLiteral("configured() true once a key is set"));

        const QJsonObject sigs = currentMachineSignals();
        // The CI/dev box should expose >=2 signals; if not, skip the machine-bound cases.
        if (sigs.size() >= 2) {
            QJsonObject lic;
            lic.insert(QStringLiteral("v"), 1);
            lic.insert(QStringLiteral("licensee"), QStringLiteral("Test Pharmacy"));
            lic.insert(QStringLiteral("signals"), sigs);
            lic.insert(QStringLiteral("issued"), QStringLiteral("2026-01-01"));
            lic.insert(QStringLiteral("expiry"), QStringLiteral("2099-12-31"));
            lic = sign(pkey, lic);

            const Licensing::Evaluation ev = Licensing::evaluate(lic);
            s.check(ev.state == QLatin1String("ok"),
                    QStringLiteral("valid license for THIS machine evaluates ok"));

            // install + check round-trip.
            const Licensing::InstallResult ins
                = Licensing::installLicense(QJsonDocument(lic).toJson(QJsonDocument::Compact));
            s.check(ins.ok, QStringLiteral("installLicense saves a valid license"));
            s.check(Licensing::check().state == QLatin1String("ok"),
                    QStringLiteral("check() reads back the installed license as ok"));

            // Expired.
            QJsonObject expired = lic;
            expired.remove(QStringLiteral("sig"));
            expired.insert(QStringLiteral("expiry"), QStringLiteral("2000-01-01"));
            expired = sign(pkey, expired);
            s.check(Licensing::evaluate(expired).state == QLatin1String("expired"),
                    QStringLiteral("past-expiry license is expired"));

            // Wrong machine: bind bogus signals (validly signed, still rejected).
            QJsonObject wrong;
            wrong.insert(QStringLiteral("v"), 1);
            wrong.insert(QStringLiteral("signals"),
                         QJsonObject{{QStringLiteral("machine_id"), QStringLiteral("zzz")},
                                     {QStringLiteral("mac"), QStringLiteral("yyy")}});
            wrong.insert(QStringLiteral("expiry"), QString());
            wrong = sign(pkey, wrong);
            s.check(Licensing::evaluate(wrong).state == QLatin1String("wrong_machine"),
                    QStringLiteral("license for other signals is wrong_machine"));
        }

        // Tampering a machine-valid signature is caught regardless of signals.
        QJsonObject t = fx; // fixture (signed by the python key, not testPub)
        s.check(Licensing::evaluate(t).state == QLatin1String("bad_signature"),
                QStringLiteral("license signed by a different key is bad_signature"));

        EVP_PKEY_free(pkey);
        Licensing::setPublicKeyForTesting(savedKey); // restore unlocked state
    }
    s.check(!Licensing::configured(),
            QStringLiteral("configured() false again after clearing the test key"));

    // ── 3) Fingerprint sanity ────────────────────────────────────────────────
    const QString code = MachineFingerprint::fingerprintCode();
    s.check(code.startsWith(QStringLiteral("PD-")),
            QStringLiteral("fingerprint code is PD-prefixed"));
    s.check(code.size() == 22, QStringLiteral("fingerprint code is PD- + 4x4 groups"));
    s.check(MachineFingerprint::fingerprintCode() == code,
            QStringLiteral("fingerprint code is deterministic"));

    // build_request is base64 of a JSON object carrying signals.
    bool reqOk = false;
    const QByteArray reqJson = QByteArray::fromBase64(Licensing::buildRequest().toLatin1());
    const QJsonObject req = QJsonDocument::fromJson(reqJson).object();
    reqOk = req.contains(QStringLiteral("signals")) && req.value(QStringLiteral("v")).toInt() == 1;
    s.check(reqOk, QStringLiteral("buildRequest is base64 JSON with v + signals"));

    return s;
}

} // namespace pharmadesk_tests
